import {
  Bot,
  Boxes,
  CircleSlash2,
  CodeXml,
  CreditCard,
  FileCode2,
  FileText,
  ListChecks,
  PackageCheck,
  Puzzle,
  ScrollText,
  ShieldCheck,
  Sparkles,
  TerminalSquare,
  type LucideIcon,
} from "lucide-react";
import {
  siAstro,
  siBetterauth,
  siBiome,
  siBun,
  siClerk,
  siCloudflareworkers,
  siConvex,
  siDocker,
  siDrizzle,
  siExpo,
  siExpress,
  siFastify,
  siGit,
  siHono,
  siLefthook,
  siModelcontextprotocol,
  siMongodb,
  siMongoose,
  siMysql,
  siNeon,
  siNextdotjs,
  siNodedotjs,
  siNpm,
  siNuxt,
  siNx,
  siOpentui,
  siPlanetscale,
  siPnpm,
  siPostgresql,
  siPrisma,
  siReactrouter,
  siSolid,
  siSqlite,
  siSupabase,
  siSvelte,
  siTanstack,
  siTauri,
  siTrpc,
  siTurborepo,
  siTurso,
  siVercel,
  siVite,
  siWxt,
  type SimpleIcon,
} from "simple-icons";

const brandIcons: Record<string, SimpleIcon> = {
  "better-auth": siBetterauth,
  astro: siAstro,
  biome: siBiome,
  bun: siBun,
  clerk: siClerk,
  cloudflare: siCloudflareworkers,
  convex: siConvex,
  d1: siCloudflareworkers,
  docker: siDocker,
  drizzle: siDrizzle,
  express: siExpress,
  fastify: siFastify,
  git: siGit,
  hono: siHono,
  lefthook: siLefthook,
  mcp: siModelcontextprotocol,
  mongodb: siMongodb,
  "mongodb-atlas": siMongodb,
  mongoose: siMongoose,
  mysql: siMysql,
  "native-bare": siExpo,
  "native-unistyles": siExpo,
  "native-uniwind": siExpo,
  neon: siNeon,
  next: siNextdotjs,
  node: siNodedotjs,
  npm: siNpm,
  nuxt: siNuxt,
  nx: siNx,
  opentui: siOpentui,
  planetscale: siPlanetscale,
  pnpm: siPnpm,
  postgres: siPostgresql,
  prisma: siPrisma,
  "prisma-postgres": siPrisma,
  "react-router": siReactrouter,
  "self-astro": siAstro,
  "self-next": siNextdotjs,
  "self-nuxt": siNuxt,
  "self-solid": siSolid,
  "self-svelte": siSvelte,
  "self-tanstack-start": siTanstack,
  solid: siSolid,
  sqlite: siSqlite,
  supabase: siSupabase,
  svelte: siSvelte,
  "tanstack-router": siTanstack,
  "tanstack-start": siTanstack,
  tauri: siTauri,
  trpc: siTrpc,
  turborepo: siTurborepo,
  turso: siTurso,
  vercel: siVercel,
  "vite-plus": siVite,
  workers: siCloudflareworkers,
  wxt: siWxt,
};

const semanticIcons: Record<string, LucideIcon> = {
  ai: Bot,
  basic: PackageCheck,
  electrobun: Boxes,
  elysia: Sparkles,
  evlog: ScrollText,
  fumadocs: FileText,
  husky: ShieldCheck,
  none: CircleSlash2,
  orpc: CodeXml,
  oxlint: FileCode2,
  polar: CreditCard,
  pwa: Puzzle,
  skills: Sparkles,
  starlight: FileText,
  todo: ListChecks,
  ultracite: ShieldCheck,
};

export function TechIcon({ id, name }: { id: string; name: string }) {
  const brand = brandIcons[id];
  if (brand) {
    return (
      <svg className="tech-icon" role="img" aria-label={`${name} icon`} viewBox="0 0 24 24">
        <path fill={`#${brand.hex}`} d={brand.path} />
      </svg>
    );
  }

  const SemanticIcon = semanticIcons[id] ?? TerminalSquare;
  return <SemanticIcon className="tech-icon semantic-icon" aria-label={`${name} icon`} />;
}
